interpolation
no-audio-display
vo=gpu-next
gpu-api=vulkan
hdr-compute-peak
target-peak=1300
target-prim=bt.2020
target-trc=pq
inverse-tone-mapping=yes
tone-mapping=spline
target-colorspace-hint=auto

