[settings.npm]
package_manager = "aube"

[settings]
plugin_autoupdate_last_check_duration = "2000d"

[tools]
aube = "latest"
bun = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:husky" = "latest"
"npm:opencode-ai" = "latest"
"pipx:yt-dlp" = "latest"
"npm:@vercel/vc-native" = "latest"
pnpm = "latest"
uv = "latest"
rust = "latest"
"cargo:cargo-binstall" = "latest"
"cargo:create-tauri-app" = "latest"
"cargo:tauri-cli" = "2"
rust-analyzer = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
usage = "latest"
"npm:@opencode-ai/cli" = {version = "next", npm_args = "--ignore-scripts=false", bun_args = "--trust"}
"cargo:dysk" = "latest"
"npm:wrangler" = "latest"
ollama = "0.32.13"
