# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        14.0

# Window
window_padding_width 1
hide_window_decorations yes
background_opacity 1.0
# background_blur 1          # only visible when background_opacity < 1.0

# Cursor
cursor_shape block
cursor_blink_interval 1
cursor_trail 1

# Scrollback
scrollback_lines 3000

# Behaviour
copy_on_select yes
strip_trailing_spaces smart
shell_integration enabled

# Tabs
tab_bar_style powerline
tab_bar_align left

# Keys
map ctrl+shift+n new_window
map ctrl+t       new_tab
map ctrl+plus    change_font_size all +1.0
map ctrl+minus   change_font_size all -1.0
map ctrl+0       change_font_size all 0
