# set prefix to be C-a
set -g prefix C-a
unbind C-b


# set delay between prefix and command
set -s escape-time 1

# set base index for windows to 1 instead of 0
set -g base-index 1

# set base index for panes to be 1 instead of 0
set -w -g pane-base-index 1

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Configuration reloaded"

# double C-a sends C-a to inside
bind C-a send-prefix

bind | split-window -h
bind - split-window -v



# hjkl moves pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# C-h and C-l change windoA
bind C-h select-window -t :-
bind C-l select-window -t :+


# hjkl resizing, repeatable
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# disable mouse 
set -g mouse off


# default terminal
set -g default-terminal "xterm-256color"

# 32 bit rgb
set -a terminal-overrides ",*256col*:RGB"

set -g status-style fg=white,bold,bg=black
set -g window-status-style fg=cyan,bg=black
set -g window-status-current-style fg=white,bold,bg=cyan
set -w -g pane-border-style fg=green,bg=black
set -w -g pane-active-border-style fg=black,bg=yellow

set -g pane-border-indicators arrows
set -g window-style dg=color240,bg=color235
set -g window-active-style fg=white,bg=black
set -g message-style fg=white,bg=color242,bold
set -g status-left "#[bg=color242]Session: #S"
set -g status-right ""
set -g status-justify centre
set -g status-position top
set -g status-interval 60

set -w -g monitor-activity on
set -w -g visual-activity on
set -g history-limit 1000000

