[settings.npm]
package_manager = "aube"

[settings]
plugin_autoupdate_last_check_duration = "2000d" #  do not check!

[tools]
aube = "latest"
bun = "latest"
"npm:@anthropic-ai/claude-code" = {version="latest", allow_builds = true}
"npm:opencode-with-claude" = {version="latest", allow_builds = true}

"npm:husky" = "latest"
"npm:opencode-ai" =  {version="latest", allow_builds = true}

"pipx:yt-dlp" = "latest"
"npm:@vercel/vc-native" = "latest"
pnpm = "latest"
uv = "latest"
# rust = "latest"
rust = "nightly"
"cargo:cargo-binstall" = "latest"
"cargo:create-tauri-app" = "latest"
"cargo:tauri-cli" = "2"
rust-analyzer = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
usage = "latest"
"npm:@opencode-ai/cli" = {version = "next", allow_builds=true}
"cargo:dysk" = "latest"
"npm:wrangler" = "latest"
ollama = "0.32.13"
"cargo:eza" = "latest"
gofumpt = "latest"
stylua = "latest"
"npm:prettier" = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
rtk = "latest"
herdr = "latest"
